routes/web.php
<?php

use App\Http\Controllers\CitasUsuarioController;
use App\Http\Controllers\EspecialidadeController;
use App\Http\Controllers\PacienteController;
use App\Http\Controllers\RegistarCitaController;
use App\Http\Controllers\MedicoController;
use App\Http\Controllers\HorarioController;
use App\Http\Controllers\MedicoCantidadController;
use App\Http\Controllers\MedicoFechaController;
use App\Http\Controllers\MedicoUsuarioController;
use App\Http\Controllers\PacienteUsuarioController;
use App\Models\Especialidade;
use App\Models\RegistrarCita;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('inicioUsuarios/inicio');
});

Route::resource('pacientes', PacienteController::class);

Route::resource('citas',  RegistarCitaController::class);

Route::resource('citasUsuario',  CitasUsuarioController::class);
Route::resource('medicos', MedicoController::class);
#Route::resource('medicos.horarios', MedicoController::class);

Route::get('medicos/horas/{id}', [MedicoController::class, 'horas'])->name('medicos.horas');
Route::get('medicos/{id}/horas/', [MedicoController::class, 'horas'])->name('medicos.horas');
Route::post('medicos/graficas', [MedicoController::class, 'graficas'])->name('medicos.graficas');
Route::resource('medicoCantidad', MedicoCantidadController::class);
Route::resource('medicoFecha', MedicoFechaController::class);
//Route::get('medicoCantidad/fechaCantidad}', [MedicoCantidadController::class, 'fechaCantidad'])->name('medicoCantidad.fechaCantidad');
Route::resource('medicosUsuario', MedicoUsuarioController::class);

Route::resource('horarios', HorarioController::class);

Route::resource('especialidades', EspecialidadeController::class);

Route::resource('pacienteUsuario', PacienteUsuarioController::class);

Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/plantilla/principal.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Citas-Medicas</title>
    <link rel="stylesheet" href="{{ asset('https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/nucleo/css/nucleo.css')}}" type="text/css">
    <link rel="stylesheet" href="{{ asset('assets/vendor/@fortawesome/fontawesome-free/css/all.min.css')}}" type="text/css">
    <link rel="stylesheet" href="{{ asset('assets/css/argon.css?v=1.2.0')}}" type="text/css">
</head>

<body>
    <nav class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white" id="sidenav-main">
        <div class="scrollbar-inner">
            <div class="sidenav-header  align-items-center">
                <a class="navbar-brand" href="javascript:void(0)">
                    <img src="{{ asset('assets/img/brand/blue.png') }}" class="navbar-brand-img" alt="...">
                </a>
            </div>
            <div class="navbar-inner">
                <div class="collapse navbar-collapse" id="sidenav-collapse-main">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" href="#">
                                <i class="ni ni-tv-2 text-primary"></i>
                                <span class="nav-link-text">Inicio</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " href="{{ route('pacientes.index') }}">
                                <i class="ni ni-single-02 text-primary "></i>
                                <span class="nav-link-text">Registrar Pacientes</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " href="{{ route('citas.index') }}">
                                <i class="ni ni-collection text-primary "></i>
                                <span class="nav-link-text">Registrar Citas</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " href="{{ route('medicos.index') }}">
                                <i class="ni ni-single-02 text-primary "></i>
                                <span class="nav-link-text">Registrar Medicos</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " href="{{ route('especialidades.index') }}">
                                <i class="ni ni-single-02 text-primary "></i>
                                <span class="nav-link-text">Registrar Especialidades</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " href="{{ route('horarios.index') }}">
                                <i class="ni ni-single-02 text-primary "></i>
                                <span class="nav-link-text">Registrar Horarios Medicos</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " href="#">
                                <i class="ni ni-single-02 text-primary "></i>
                                <span class="nav-link-text">cantidad Citas Medicos</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " href="#">
                                <i class="ni ni-single-02 text-primary "></i>
                                <span class="nav-link-text">Busacar citas por fecha</span>
                            </a>
                        </li>
                    </ul>
                    <hr class="my-3">
                </div>
            </div>
        </div>
    </nav>
    <div class="main-content" id="panel">
        <nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
            <div class="container-fluid">
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <form class="navbar-search navbar-search-light form-inline mr-sm-3" id="navbar-search-main">
                        <div class="form-group mb-0">
                            <div class="input-group input-group-alternative input-group-merge">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-search"></i></span>
                                </div>
                                <input class="form-control" placeholder="buscar" type="text">
                            </div>
                        </div>
                        <button type="button" class="close" data-action="search-close" data-target="#navbar-search-main"
                            aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </form>
                    <ul class="navbar-nav align-items-center  ml-md-auto ">
                        <li class="nav-item d-xl-none">
                            <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin"
                                data-target="#sidenav-main">
                                <div class="sidenav-toggler-inner">
                                    <i class="sidenav-toggler-line"></i>
                                    <i class="sidenav-toggler-line"></i>
                                    <i class="sidenav-toggler-line"></i>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item d-sm-none">
                            <a class="nav-link" href="#" data-action="search-show" data-target="#navbar-search-main">
                                <i class="ni ni-zoom-split-in"></i>
                            </a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Inicio Sesion') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Registro') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    <i class="ni ni-user-run"></i>
                                        {{ __('cerrar session') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <div class="header bg-primary pb-6">
            <div class="container-fluid" >
                <div class="header-body">
                    <div class="row align-items-center py-4">
                        <div class="col-lg-6 col-7">

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container-fluid mt--6">
            <div class="row">
                <!-- todo el contenido  aqui -->
                @yield('contenido')
            </div>
            <!-- Footer -->
            <footer class="footer pt-0">
                <div class="row align-items-center justify-content-lg-between">
                    <div class="col-lg-6">
                        <div class="copyright text-center  text-lg-left  text-muted">
                            &copy; 2021 <a href="#" class="font-weight-bold ml-1"
                                target="_blank">proyecto Com450</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="{{ asset('assets/vendor/jquery/dist/jquery.min.js')}}"></script>
    <script src="{{ asset('assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js')}}"></script>
    <script src="{{ asset('assets/vendor/js-cookie/js.cookie.js')}}"></script>
    <script src="{{ asset('assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js')}}"></script>
    <script src="{{ asset('assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js')}}"></script>
    <!-- Optional JS -->
    <script src="{{ asset('assets/vendor/chart.js/dist/Chart.min.js')}}"></script>
    <script src="{{ asset('assets/vendor/chart.js/dist/Chart.extension.js')}}"></script>
    <!-- Argon JS -->
    <script src="{{ asset('assets/js/argon.js?v=1.2.0')}}"></script>


</body>

</html>