routes/web.php
<?php

use App\Http\Controllers\CitasUsuarioController;
use App\Http\Controllers\EspecialidadeController;
use App\Http\Controllers\PacienteController;
use App\Http\Controllers\RegistarCitaController;
use App\Http\Controllers\MedicoController;
use App\Http\Controllers\HorarioController;
use App\Http\Controllers\MedicoCantidadController;
use App\Http\Controllers\MedicoFechaController;
use App\Http\Controllers\MedicoUsuarioController;
use App\Http\Controllers\PacienteUsuarioController;
use App\Models\Especialidade;
use App\Models\RegistrarCita;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('inicioUsuarios/inicio');
});

Route::resource('pacientes', PacienteController::class);

Route::resource('citas',  RegistarCitaController::class);

Route::resource('citasUsuario',  CitasUsuarioController::class);
Route::resource('medicos', MedicoController::class);
#Route::resource('medicos.horarios', MedicoController::class);

Route::get('medicos/horas/{id}', [MedicoController::class, 'horas'])->name('medicos.horas');
Route::get('medicos/{id}/horas/', [MedicoController::class, 'horas'])->name('medicos.horas');
Route::post('medicos/graficas', [MedicoController::class, 'graficas'])->name('medicos.graficas');
Route::resource('medicoCantidad', MedicoCantidadController::class);
Route::resource('medicoFecha', MedicoFechaController::class);
//Route::get('medicoCantidad/fechaCantidad}', [MedicoCantidadController::class, 'fechaCantidad'])->name('medicoCantidad.fechaCantidad');
Route::resource('medicosUsuario', MedicoUsuarioController::class);

Route::resource('horarios', HorarioController::class);

Route::resource('especialidades', EspecialidadeController::class);

Route::resource('pacienteUsuario', PacienteUsuarioController::class);

Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Especialidade.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Especialidade extends Model
{
    use HasFactory;
    protected $table = 'especialidades';
    protected $fillable = [
        'nombre',
        'precio'
    ];
}

app/Http/Controllers/EspecialidadeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Especialidade;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Redirect;


class EspecialidadeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $especialidades = Especialidade::orderby('id','asc')
        ->select('*')
        ->get();
        return view('especialidades.index', ['especialidades' => $especialidades]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("especialidades.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $inputs= $request->all();
        $especialidades = Especialidade::create($inputs);
        $especialidades->save();
        return redirect()->route('especialidades.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Especialidade  $especialidade
     * @return \Illuminate\Http\Response
     */
    public function show(Especialidade $especialidade)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Especialidade  $especialidade
     * @return \Illuminate\Http\Response
     */
    public function edit( $id)
    {
        $especialidad = Especialidade::findOrFail($id);
        return view('especialidades.edit', ['especialidad'=>$especialidad]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Especialidade  $especialidade
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Especialidade $especialidad)
    {
        $especialidad = Especialidade::find($request->input('id'));

        $especialidad->fill($request->input());
        $especialidad->saveOrFail();
        return Redirect::to('especialidades');
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Especialidade  $especialidade
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Especialidade::destroy($id);
        return Redirect::to('especialidades');
    }
}

resources/views/especialidades/create.blade.php
@extends('plantilla.principal')

@section('contenido')
    <div class="col-xl-7">
        <div class="card">
            <div class="card-body">
                <div class="row align-items-center">
                    <div class="col-6">
                        <h3 class="my-5 ml-4">Registar Especialidades</h3>
                    </div>
                </div>
                <form action="{{ route('especialidades.store') }}" method="POST">
                    {{ csrf_field() }}
                    <div class="pl-lg-4 ml-4">
                        <div class="row">
                            <div class="col-lg-10">
                                <div class="form-group">
                                    <label class="form-control-label" for="nombre">Especialidad</label>
                                    <input type="text" id="nombre" name="nombre" class="form-control" placeholder="Nombre Especialidad" required>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-10">
                                <div class="form-group">
                                    <label class="form-control-label" for="precio">Precio</label>
                                    <input type="number" id="precio" name="precio" class="form-control" placeholder="precio" required>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="offset-4">
                            <button class="btn btn-icon btn-primary " type="submit">
                                <span class="btn-inner--icon"><i class="ni ni-fat-add"></i></span>
                                <span class="btn-inner--text">Agregar</span>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col-xl-5">
        <div class="card">
            <div class="card-body">
                <img src="{{ asset('images\img2.svg') }} " class="ml-5" alt="" width="350px" height="300px">
            </div>
        </div>
    </div>

@endsection

resources/views/especialidades/edit.blade.php
@extends('plantilla.principal')

@section('contenido')
    <div class="col-xl-7">
        <div class="card">
            <div class="card-body">
                <div class="row align-items-center">
                    <div class="col-6">
                        <h3 class="my-5 ml-4">Editar Especialidades</h3>
                    </div>
                </div>
                <form action="{{ route('especialidades.update', $especialidad) }}" method="POST">
                    {{ csrf_field() }}
                    @method('PUT')
                    <div class="pl-lg-4 ml-4">
                        <div class="row">
                            <input type="hidden" id="id" name="id" class="form-control" value="{{ $especialidad->id }}">
                            <div class="col-lg-10">
                                <div class="form-group">
                                    <label class="form-control-label" for="nombre">Especialidad</label>
                                    <input type="text" id="nombre" name="nombre" class="form-control" value="{{ $especialidad->nombre }}">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-10">
                                <div class="form-group">
                                    <label class="form-control-label" for="precio">Precio</label>
                                    <input type="number" id="precio" name="precio" class="form-control" value="{{ $especialidad->precio }}">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="offset-4">
                            <button class="btn btn-icon btn-primary " type="submit">
                                <span class="btn-inner--icon"><i class="ni ni-fat-add"></i></span>
                                <span class="btn-inner--text">Agregar</span>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col-xl-5">
        <div class="card">
            <div class="card-body">
                <img src="{{ asset('images\img2.svg') }} " class="ml-5" alt="" width="350px" height="300px">
            </div>
        </div>
    </div>

@endsection

resources/views/especialidades/index.blade.php
@extends('plantilla.principal')

@section('contenido')
    <div class="col">
        <div class="card bg-default shadow">
            <div class="card-header bg-transparent border-0">
                <div class="row">
                    <div class="col-9">
                        <h3 class="text-white mb-0">Lista Especialidades</h3>
                    </div>
                    <div class="col-3">
                        <a class="btn btn-icon btn-primary " type="button" href="{{ route('especialidades.create') }}">
                            <span class="btn-inner--icon"><i class="ni ni-fat-add"></i></span>
                            <span class="btn-inner--text">Agregar Nuevo</span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table align-items-center table-dark table-flush">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col" class="sort" data-sort="name">N°</th>
                            <th scope="col" class="sort" data-sort="name">Especialidad</th>
                            <th scope="col" class="sort" data-sort="budget">Precio</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody class="list">
                        @foreach ($especialidades as $especialidad)
                            <tr>
                                <td class="budget">{{ $especialidad->id }}</td>
                                <td class="budget">{{ $especialidad->nombre }}</td>
                                <td class="budget">{{ $especialidad->precio }}</td>
                                <td class="text-right">
                                    <div class="dropdown">
                                        <a class="btn btn-sm btn-icon-only text-light" href="#" role="button"
                                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="fas fa-ellipsis-v"></i>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                            <a class="dropdown-item" href="{{route('especialidades.edit',$especialidad->id)}}">Editar</a>
                                            <form  action="{{route('especialidades.destroy',$especialidad->id)}}" method="POST">
                                                {{csrf_field()}}
                                                @method('DELETE')
                                                <button  class="dropdown-item">Eliminar</button>
                                            </form>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection