routes/web.php
<?php

use App\Http\Controllers\CitasUsuarioController;
use App\Http\Controllers\EspecialidadeController;
use App\Http\Controllers\PacienteController;
use App\Http\Controllers\RegistarCitaController;
use App\Http\Controllers\MedicoController;
use App\Http\Controllers\HorarioController;
use App\Http\Controllers\MedicoCantidadController;
use App\Http\Controllers\MedicoFechaController;
use App\Http\Controllers\MedicoUsuarioController;
use App\Http\Controllers\PacienteUsuarioController;
use App\Models\Especialidade;
use App\Models\RegistrarCita;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('inicioUsuarios/inicio');
});

Route::resource('pacientes', PacienteController::class);

Route::resource('citas',  RegistarCitaController::class);

Route::resource('citasUsuario',  CitasUsuarioController::class);
Route::resource('medicos', MedicoController::class);
#Route::resource('medicos.horarios', MedicoController::class);

Route::get('medicos/horas/{id}', [MedicoController::class, 'horas'])->name('medicos.horas');
Route::get('medicos/{id}/horas/', [MedicoController::class, 'horas'])->name('medicos.horas');
Route::post('medicos/graficas', [MedicoController::class, 'graficas'])->name('medicos.graficas');
Route::resource('medicoCantidad', MedicoCantidadController::class);
Route::resource('medicoFecha', MedicoFechaController::class);
//Route::get('medicoCantidad/fechaCantidad}', [MedicoCantidadController::class, 'fechaCantidad'])->name('medicoCantidad.fechaCantidad');
Route::resource('medicosUsuario', MedicoUsuarioController::class);

Route::resource('horarios', HorarioController::class);

Route::resource('especialidades', EspecialidadeController::class);

Route::resource('pacienteUsuario', PacienteUsuarioController::class);

Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/citas/citasPaciente.blade.php
@extends('plantilla.principal')
@section('contenido')
    <div class="col-xl-12">
        <div class="card">
            <div class="card-body">
                <div class="row align-items-center">
                    <div class="col-6">
                        <h3 class="my-5 ml-4">Registar Cita</h3>
                    </div>
                </div>
                <div class="news">
                    <div class="container">
                        <div class="alert alert-danger" role="alert">
                            Puede cancelar hasta 24h antes de la cita
                          </div>
                        <div class="row">
                            <div class="col">
                                <div class="card">
                                    <div class="card-header border-0">
                                        <h3 class="mb-0">Lista de citas para </h3>
                                    </div>
                                    <div class="table-responsive">
                                        <table class="table align-items-center table-flush">
                                            <thead class="thead-light">
                                                <tr>
                                                    <th scope="col" class="sort">nombre</th>
                                                    <th scope="col" class="sort">Fecha/Hora</th>
                                                    <th scope="col" class="sort">Médico</th>
                                                    <th scope="col" class="sort">Descripcion</th>
                                                    <th scope="col" class="sort">Estado</th>
                                                    <th scope="col" class="sort">Precio</th>
                                                    <th scope="col" class="sort">estadoPrecio</th>
                                                    <th scope="col" class="sort"></th>
                                                </tr>
                                            </thead>
                                            <tbody class="list">
                                                @foreach ($citas as $cita)
                                                    <tr>
                                                        <td class="budget">{{ $cita->name }}</td>
                                                        <td class="budget">{{ $cita->fecha_cita }}/{{ $cita->hora_cita }}</td>
                                                        <td class="budget">{{ $cita->medico_nombre }}</td>
                                                        <td class="budget">{{ $cita->asunto }}</td>
                                                        <td class="budget">{{ $cita->estado_cita }}</td>
                                                        <td class="budget">{{ $cita->precio }}</td>
                                                        @if ($cita->estado_pago == 1)
                                                            <td class="budget">Pagado</td>
                                                        @else
                                                            <td class="budget">Pendiente</td>
                                                        @endif
                                                        @if($cita->estado_cita == "Activa" || $cita->estado_cita == "Pendiente")
                                                        <td class="budget">
                                                            <a class="btn btn-danger" href="{{route('citasUsuario.edit',[$cita->id, 'estado'=>$cita->estado_cita])}}">Cancelar</a>
                                                        </td>
                                                        @else
                                                        <td class="budget">
                                                            <a class="btn btn-success" href="{{route('citasUsuario.edit',[$cita->id, 'estado'=>$cita->estado_cita])}}">Activar</a>
                                                        </td>
                                                        @endif
                                                    </tr>
                                                @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


@endsection

resources/views/citas/create.blade.php
@extends('plantilla.principal')

@section('contenido')
    <div class="col-xl-7">
        <div class="card">
            <div class="card-body">
                <div class="row align-items-center">
                    <div class="col-6">
                        <h3 class="my-5 ml-4">Registar Cita</h3>
                    </div>
                </div>
                <form action="{{ route('citas.store') }}" method="POST">
                    {{ csrf_field() }}
                    <div class="pl-lg-4 ml-4">
                        <div class="row">
                            <div class="col-lg-10">
                                <div class="form-group">
                                    <label class="form-control-label" for="asunto">Asunto</label>
                                    <input type="text" id="asunto" name="asunto" class="form-control" placeholder="asunto" required>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-10">
                                <div class="form-group">
                                    <label for="paciente">Paciente</label>
                                    <select class="form-control" id="paciente" name="paciente_id" required>
                                        @foreach ($pacientes as $paciente)
                                            <option value="{{ $paciente->id}}">{{ $paciente->nombre}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-10">
                                <div class="form-group">
                                    <label for="user">Usuario</label>
                                    <select class="form-control" id="user" name="user_id" required>
                                        @foreach ($pacientes as $paciente)
                                        <option value="{{ $paciente->user_id}}" selected>{{ $paciente->user_name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-10">
                                <div class="form-group">
                                    <label for="medico">Medico</label>
                                    <select class="form-control" id="medico" name="medico_id" required>
                                        @foreach ($medicos as $medico)
                                            <option value="{{ $medico->id }}">{{ $medico->nombre }}</option>

                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-5">
                                <div class="form-group">
                                    <label class="form-control-label" for="fecha">Fecha</label>
                                    <input type="date" id="fecha" name="fecha_cita" class="form-control" placeholder="fecha" required>
                                </div>
                            </div>
                            <div class="col-lg-5">
                                <div class="form-group">
                                    <label class="form-control-label" for="hora">Hora</label>
                                    <input type="time" id="hora" name="hora_cita" class="form-control" placeholder="hora" required>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-10">
                                <div class="form-group">
                                    <label for="estadoCita">Estado de Cita</label>
                                    <select class="form-control" id="estadoCita" name="estado_cita" required>
                                        <option value="Pendiente">Pendiente</option>
                                        <option value="Cancelada">Cancelada</option>
                                        <option value="Activa">Activa</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-10">
                                <div class="form-group">
                                    <label class="form-control-label" for="precio">Precio</label>
                                    <input type="number" id="precio" name="precio" class="form-control" placeholder="Precio" required>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-10">
                                <div class="form-group">
                                    <label for="estadoPago">Estado de Pago</label>
                                    <select class="form-control" id="estadoPago" name="estado_pago" required>
                                        <option value="0">Pendiente</option>
                                        <option value="1">Pagada</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="offset-4">
                            <button class="btn btn-icon btn-primary " type="submit">
                                <span class="btn-inner--icon"><i class="ni ni-fat-add"></i></span>
                                <span class="btn-inner--text">Agregar</span>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col-xl-5">
        <div class="card">
            <div class="card-body">
                <img src="{{ asset('images\img2.svg') }} " class="ml-5" alt="" width="350px" height="300px">
            </div>
        </div>
    </div>

@endsection

resources/views/citas/edit.blade.php
@extends('plantilla.principal')

@section('contenido')
    <div class="col-xl-7">
        <div class="card">
            <div class="card-body">
                <div class="row align-items-center">
                    <div class="col-6">
                        <h3 class="my-5 ml-4">Editar Cita</h3>
                    </div>
                </div>
                <form action="{{ route('citas.update', $cita) }}" method="POST">
                    {{ csrf_field() }}
                    @method('PUT')
                    <div class="pl-lg-4 ml-4">
                        <div class="row">
                            <div class="col-lg-10">
                                <div class="form-group">
                                    <label class="form-control-label" for="asunto">Asunto</label>
                                    <input type="text" id="asunto" name="asunto" class="form-control"
                                        value="{{ $cita->asunto }}">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-10">
                                <div class="form-group">
                                    <label for="paciente">Paciente</label>
                                    <select class="form-control" id="paciente" name="paciente_id">
                                        @foreach ($pacientes as $paciente)
                                            @if ($cita->paciente_id == $paciente->id)
                                                <option value="{{ $paciente->id }}" selected>{{ $paciente->nombre }}
                                                </option>
                                            @else
                                                <option value="{{ $paciente->id }}">{{ $paciente->nombre }}</option>
                                            @endif
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="row ">
                            <div class="col-lg-10">
                                <div class="form-group">
                                    <label for="user">Usuario</label>
                                    <select class="form-control" id="user" name="user_id">
                                        @foreach ($usuarios as $usuario)
                                            @if ($cita->user_id == $usuario->id)
                                                <option value="{{ $usuario->id }}" selected>{{ $usuario->name}}
                                                </option>
                                            @else
                                                <option value="{{ $usuario->id }}">{{ $usuario->name }}</option>
                                            @endif
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-10">
                                <div class="form-group">
                                    <label for="medico">Medico</label>
                                    <select class="form-control" id="medico" name="medico_id">
                                        @foreach ($medicos as $medico)
                                            @if ($cita->medico_id == $medico->id)
                                                <option value="{{ $medico->id }}" selected>{{ $medico->nombre }}
                                                </option>
                                            @else
                                                <option value="{{ $medico->id }}">{{ $medico->nombre }}</option>
                                            @endif
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-5">
                                <div class="form-group">
                                    <label class="form-control-label" for="fecha">Fecha</label>
                                    <input type="date" id="fecha" name="fecha_cita" class="form-control"
                                        value="{{ $cita->fecha_cita }}">
                                </div>
                            </div>
                            <div class="col-lg-5">
                                <div class="form-group">
                                    <label class="form-control-label" for="hora">Hora</label>
                                    <input type="time" id="hora" name="hora_cita" class="form-control"
                                        value="{{ $cita->hora_cita }}">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-10">
                                <div class="form-group">
                                    <label for="estadoCita">Estado de Cita</label>
                                    <select class="form-control" id="estadoCita" name="estado_cita">
                                        @if ($cita->estado_cita == 'Pendiente')
                                            <option value="Pendiente" selected>Pendiente</option>
                                            <option value="Cancelada">Cancelada</option>
                                            <option value="Activa">Activa</option>
                                        @endif
                                        @if ($cita->estado_cita == 'Cancelada')
                                            <option value="Pendiente">Pendiente</option>
                                            <option value="Cancelada" selected>Cancelada</option>
                                            <option value="Activa">Activa</option>
                                        @endif
                                        @if ($cita->estado_cita == 'Activa')
                                            <option value="Pendiente">Pendiente</option>
                                            <option value="Cancelada">Cancelada</option>
                                            <option value="Activa" selected>Activa</option>
                                        @endif
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-10">
                                <div class="form-group">
                                    <label class="form-control-label" for="precio">Precio</label>
                                    <input type="number" id="precio" name="precio" class="form-control"
                                        value="{{ $cita->precio }}">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-10">
                                <div class="form-group">
                                    <label for="estadoPago">Estado de Pago</label>
                                    <select class="form-control" id="estadoPago" name="estado_pago">
                                        @if ($cita->estado_pago == 0)
                                            <option value="0" selected>Pendiente</option>
                                            <option value="1">Pagada</option>
                                        @else
                                            <option value="1" selected>Pagada</option>
                                            <option value="0">Pendiente</option>
                                        @endif
                                    </select>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="offset-4">
                            <button class="btn btn-icon btn-primary " type="submit">
                                <span class="btn-inner--icon"><i class="ni ni-fat-add"></i></span>
                                <span class="btn-inner--text">Agregar</span>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col-xl-5">
        <div class="card">
            <div class="card-body">
                <img src="{{ asset('images\img1.svg') }} " class="ml-5" alt="" width="350px" height="300px">
            </div>
        </div>
    </div>

@endsection

resources/views/citas/index.blade.php
@extends('plantilla.principal')

@section('contenido')
    <div class="col">
        <div class="card bg-default shadow">
            <div class="card-header bg-transparent border-0">
                <div class="row">
                    <div class="col-9">
                        <h3 class="text-white mb-0">Lista Citas Registradas</h3>
                    </div>
                    <div class="col-3">
                        <a class="btn btn-icon btn-primary " type="button" href="{{ route('citas.create') }}">
                            <span class="btn-inner--icon"><i class="ni ni-fat-add"></i></span>
                            <span class="btn-inner--text">Agregar Nuevo</span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table align-items-center table-dark table-flush">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col" class="sort" data-sort="name">Numero</th>
                            <th scope="col" class="sort" data-sort="name">Asunto</th>
                            <th scope="col" class="sort" data-sort="budget">Paciente</th>
                            <th scope="col" class="sort" data-sort="status">Medico</th>
                            <th scope="col" class="sort" data-sort="status">fecha/hora</th>
                            <th scope="col" class="sort" data-sort="status">Estado Cita</th>
                            <th scope="col" class="sort" data-sort="completion">Precio</th>
                            <th scope="col" class="sort" data-sort="completion">Estado Pago</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody class="list">
                        @foreach ($citas as $cita)
                            <tr>
                                <td class="budget">{{ $cita->id}}</td>
                                <td class="budget">{{ $cita->asunto }}</td>
                                <td class="budget">{{ $cita->paciente_nombre }}</td>
                                <td class="budget">{{ $cita->medico_nombre}}</td>
                                <td class="budget">{{ $cita->fecha_cita }}/{{ $cita->hora_cita }}</td>
                                <td class="budget">{{ $cita->estado_cita }}</td>
                                <td class="budget">{{ $cita->precio }}</td>
                                @if($cita->estado_pago == 1)
                                    <td class="budget">Pagado</td>
                                @else
                                    <td class="budget">Pendiente</td>
                                @endif
                                    <td class="text-right">
                                    <div class="dropdown">
                                        <a class="btn btn-sm btn-icon-only text-light" href="#" role="button"
                                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="fas fa-ellipsis-v"></i>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                            <a class="dropdown-item" href="{{route('citas.edit',$cita->id)}}">Editar</a>
                                            <form  action="{{route('citas.destroy',$cita->id)}}" method="POST">
                                                {{csrf_field()}}
                                                @method('DELETE')
                                                <button  class="dropdown-item">Eliminar</button>
                                            </form>
                                            @if($cita->estado_cita == "Activa" || $cita->estado_cita == "Pendiente")
                                                <a class="dropdown-item" href="{{route('citasUsuario.edit',[$cita->id, 'estado'=>$cita->estado_cita])}}">Cancelar Cita</a>
                                            @else
                                                <a class="dropdown-item" href="{{route('citasUsuario.edit',[$cita->id, 'estado'=>$cita->estado_cita])}}">Activar Cita</a>
                                            @endif

                                        </div>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@push('myjs')
@endpush