routes/web.php
<?php

use App\Http\Controllers\CitasUsuarioController;
use App\Http\Controllers\EspecialidadeController;
use App\Http\Controllers\PacienteController;
use App\Http\Controllers\RegistarCitaController;
use App\Http\Controllers\MedicoController;
use App\Http\Controllers\HorarioController;
use App\Http\Controllers\MedicoCantidadController;
use App\Http\Controllers\MedicoFechaController;
use App\Http\Controllers\MedicoUsuarioController;
use App\Http\Controllers\PacienteUsuarioController;
use App\Models\Especialidade;
use App\Models\RegistrarCita;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('inicioUsuarios/inicio');
});

Route::resource('pacientes', PacienteController::class);

Route::resource('citas',  RegistarCitaController::class);

Route::resource('citasUsuario',  CitasUsuarioController::class);
Route::resource('medicos', MedicoController::class);
#Route::resource('medicos.horarios', MedicoController::class);

Route::get('medicos/horas/{id}', [MedicoController::class, 'horas'])->name('medicos.horas');
Route::get('medicos/{id}/horas/', [MedicoController::class, 'horas'])->name('medicos.horas');
Route::post('medicos/graficas', [MedicoController::class, 'graficas'])->name('medicos.graficas');
Route::resource('medicoCantidad', MedicoCantidadController::class);
Route::resource('medicoFecha', MedicoFechaController::class);
//Route::get('medicoCantidad/fechaCantidad}', [MedicoCantidadController::class, 'fechaCantidad'])->name('medicoCantidad.fechaCantidad');
Route::resource('medicosUsuario', MedicoUsuarioController::class);

Route::resource('horarios', HorarioController::class);

Route::resource('especialidades', EspecialidadeController::class);

Route::resource('pacienteUsuario', PacienteUsuarioController::class);

Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Medico.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Medico extends Model
{
    use HasFactory;
    protected $table = 'medicos';
    protected $fillable = [
        'nombre',
        'apellido',
        'genero',
        'fecha_nacimiento',
        'direccion',
        'telefono',
        'especialidad_id',
    ];
}

app/Http/Controllers/MedicoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Especialidade;
use App\Models\Horario;
use App\Models\Medico;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class MedicoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        //$this->middleware('auth');
    }
    public function index()
    {
        # $medicos=Medico::orderby('id','desc')->paginate();
        $medicos = Medico::orderby('id', 'desc')
            ->join('especialidades', 'medicos.especialidad_id', '=', 'especialidades.id')
            ->select('medicos.*', 'especialidades.nombre as especialidades_nombre')
            ->get();
        return view('medicos.index', ['medicos' => $medicos]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $especialidades = DB::table('especialidades')
            ->select("*")
            ->get();
        return view("medicos.create", ['especialidades' => $especialidades]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $inputs = $request->all();
        $medico = Medico::create($inputs);
        $medico->save();
        return redirect()->route('medicos.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Medico  $medico
     * @return \Illuminate\Http\Response
     */
    public function show(Medico $medico)
    {
        //
        $especialidad = Especialidade::findOrFail($medico->especialidad_id);

        return view("medicos.show", ['medico' => $medico, 'especialidad' => $especialidad]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Medico  $medico
     * @return \Illuminate\Http\Response
     */
    public function edit(Medico $medico)
    {
        //
        $especialidades = DB::table('especialidades')
            ->select("*")
            ->get();
        return view("medicos.edit", ['medico' => $medico, 'especialidades' => $especialidades]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Medico  $medico
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Medico $medico)
    {
        $especialidad = Especialidade::findOrFail($medico->especialidad_id);
        $medico->fill($request->input());
        $medico->saveOrFail();
        return view('medicos.show', ['medico' => $medico, 'especialidad' => $especialidad]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Medico  $medico
     * @return \Illuminate\Http\Response
     */
    public function destroy(Medico $medico)
    {
        $medico->delete();

        return redirect()->route('medicos.index');
    }
    
    public function horas($id)
    {
        $medico = Medico::findOrFail($id);
        $horas_cumplidas = DB::select('SELECT SEC_TO_TIME(SUM( TIME_TO_SEC(TIMEDIFF(hora_salida,hora_entrada))))as hora FROM horarios WHERE medico_id =' . $id);
        return view('medicos.horas', ['medico' => $medico, 'horas_cumplidas' => $horas_cumplidas[0]]);
    }
}

resources/views/medicos/cantidad.blade.php
@extends('plantilla.principal')

@section('contenido')
    <div class="col-6">
        <div class="col">
            <div class="card bg-default shadow">
                <div class="card-header bg-transparent border-0">
                    <div class="row">
                        <div class="col-9">
                            <h3 class="text-white mb-0">Cantidad De citas (Reservas)</h3>
                        </div>
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table align-items-center table-dark table-flush" id='medicos'>
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col" class="sort" data-sort="name">Nombre</th>
                                <th scope="col" class="sort" data-sort="name">Cantidad</th>
                            </tr>
                        </thead>
                        <tbody class="list" id='myTable'>
                            @foreach ($medicos as $medico)
                                <tr>
                                    <td class="budget">{{ $medico->nombre }}</td>
                                    <td class="budget">{{ $medico->cantidad_citas }}</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-6">
        <div class="card">
            <div class="card-body">
                <canvas id="myChart" width="400" height="400"></canvas>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    <script>
        let medicos_td = document.querySelectorAll('td');
        let citas_td = document.querySelectorAll('td + td');
        var citas = [];
        var medicos = [];
        for (let i = 0; i < medicos_td.length; i = i + 2) {
            medicos.push(medicos_td[i].firstChild.data);
        }
        for (let i = 0; i < citas_td.length; i++) {
            citas.push(parseInt(citas_td[i].firstChild.data));
        }

        var ctx = document.getElementById('myChart').getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: medicos,
                datasets: [{
                    label: 'cantidad citas medicas',
                    data: citas,
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }],
            },
        }
        });
    </script>
@endsection

@push('myjs')
@endpush

resources/views/medicos/cantidad_cita.blade.php
@extends('plantilla.principal')

@section('contenido')
    <div class="col-xl-7">
        <div class="card">
            <div class="card-body">
                <div class="row align-items-center">
                    <div class="col-6">
                        <h3 class="my-5 ml-4">buscar cantidad citas entre fechas</h3>
                    </div>
                </div>
                <form action="{{ route('medicoFecha.store') }}" method="POST">
                    {{ csrf_field() }}
                    <div class="pl-lg-4 ml-4">

                        <div class="row">
                            <div class="col-lg-5">
                                <div class="form-group">
                                    <label class="form-control-label" for="fecha_inicio">fecha Inicio</label>
                                    <input type="date" id="fecha_inicio" name="fecha_inicio" class="form-control" placeholder="fecha_inicio">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-5">
                                <div class="form-group">
                                    <label class="form-control-label" for="fecha_final">Fecha Final</label>
                                    <input type="date" id="fecha_final" name="fecha_final" class="form-control" placeholder="fecha_final">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="offset-4">
                            <button class="btn btn-icon btn-primary " type="submit">
                                <span class="btn-inner--icon"><i class="ni ni-fat-add"></i></span>
                                <span class="btn-inner--text">buscar</span>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col-xl-5">
        <div class="card">
            <div class="card-body">
                <img src="{{ asset('images\img2.svg') }} " class="ml-5" alt="" width="350px" height="300px">
            </div>
        </div>
    </div>

@endsection

resources/views/medicos/create.blade.php
@extends('plantilla.principal')

@section('contenido')
    <div class="col-xl-7">
        <div class="card">
            <div class="card-body">
                <div class="row align-items-center">
                    <div class="col-6">
                        <h3 class="my-5 ml-4">Registar Medico</h3>
                    </div>
                </div>
                <form action="{{ route('medicos.store') }}" method="POST">
                    {{ csrf_field() }}
                    <div class="pl-lg-4 ml-4">
                        <div class="row">
                            <div class="col-lg-10">
                                <div class="form-group">
                                    <label class="form-control-label" for="nombre">Nombre</label>
                                    <input type="text" id="nombre" name="nombre" class="form-control" placeholder="nombre" required>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-10">
                                <div class="form-group">
                                    <label class="form-control-label" for="apellido">Apellido</label>
                                    <input type="text" id="apellido" name="apellido" class="form-control" placeholder="apellido" required>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-10">
                                <div class="form-group">
                                    <div class="maxl">
                                        <label class="radio inline">
                                            <input type="radio" name="genero" value="M" checked>
                                            <span> Masculino </span>
                                        </label>
                                        <label class="radio inline">
                                            <input type="radio" name="genero" value="F" >
                                            <span> Femenino </span>
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-5">
                                <div class="form-group">
                                    <label class="form-control-label" for="fecha_nacimiento">Fecha de nacimento</label>
                                    <input type="date" id="fecha_nacimiento" name="fecha_nacimiento" class="form-control" placeholder="fecha_nacimiento" required>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-10">
                                <div class="form-group">
                                    <label class="form-control-label" for="direccion">Direccion</label>
                                    <input type="text" id="direccion" name="direccion" class="form-control" placeholder="direccion" required>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-10">
                                <div class="form-group">
                                    <label class="form-control-label" for="telefono">Telefono</label>
                                    <input type="text" id="telefono" name="telefono" class="form-control" placeholder="telefono" required>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-10">
                                <div class="form-group">
                                    <label for="medico">Especialidades</label>
                                    <select class="form-control" id="especialidad_id" name="especialidad_id" required>
                                        @foreach ($especialidades as $especialidad)
                                            <option value="{{ $especialidad->id }}">{{ $especialidad->nombre }}</option>

                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="offset-4">
                            <button class="btn btn-icon btn-primary " type="submit">
                                <span class="btn-inner--icon"><i class="ni ni-fat-add"></i></span>
                                <span class="btn-inner--text">Agregar</span>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col-xl-5">
        <div class="card">
            <div class="card-body">
                <img src="{{ asset('images\img2.svg') }} " class="ml-5" alt="" width="350px" height="300px">
            </div>
        </div>
    </div>

@endsection

resources/views/medicos/edit.blade.php
@extends('plantilla.principal')

@section('contenido')
    <div class="col-xl-7">
        <div class="card">
            <div class="card-body">
                <div class="row align-items-center">
                    <div class="col-6">
                        <h3 class="my-5 ml-4">Editar Paciente</h3>
                    </div>
                </div>
                <form action="{{ route('medicos.update', $medico) }}" method="POST">
                    {{ csrf_field() }}
                    @method('PUT')
                    <div class="pl-lg-4 ml-4">
                        <div class="row">
                            <div class="col-lg-10">
                                <div class="form-group">
                                    <label class="form-control-label" for="nombre">Nombre</label>
                                    <input type="text" id="nombre" name="nombre" class="form-control" placeholder="nombre"
                                        value="{{ $medico->nombre }}">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-10">
                                <div class="form-group">
                                    <label class="form-control-label" for="apellido">Apellido</label>
                                    <input type="text" id="apellido" name="apellido" class="form-control"
                                        placeholder="apellido" value="{{ $medico->apellido }}">
                                </div>
                            </div>
                        </div>


                        @if ($medico->genero=='M')
                            @php ($hombre = 'checked')
                            @php ($mujer = '')
                        @else
                            @php ($hombre = '')
                            @php ($mujer = 'checked')
                        @endif 
                        <div class="row">
                            <div class="col-lg-10">
                                <div class="form-group">
                                    <label class="radio inline">
                                        <input type="radio" name="genero" value="M" {{ $hombre }}>
                                        <span> Masculino </span>
                                    </label>
                                    <label class="radio inline">
                                        <input type="radio" name="genero" value="F" {{ $mujer }}>
                                        <span>Femenino </span>
                                    </label>
                                </div>
                            </div>
                        </div>


                        <div class="row">
                            <div class="col-lg-5">
                                <div class="form-group">
                                    <label class="form-control-label" for="fecha_nacimiento">Fecha de nacimento</label>
                                    <input type="date" id="fecha_nacimiento" name="fecha_nacimiento" class="form-control"
                                        placeholder="fecha_nacimiento" value="{{ $medico->fecha_nacimiento }}">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-10">
                                <div class="form-group">
                                    <label class="form-control-label" for="direccion">Direccion</label>
                                    <input type="text" id="direccion" name="direccion" class="form-control"
                                        placeholder="direccion" value="{{ $medico->direccion }}">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-10">
                                <div class="form-group">
                                    <label class="form-control-label" for="telefono">Telefono</label>
                                    <input type="text" id="telefono" name="telefono" class="form-control"
                                        placeholder="telefono" value="{{ $medico->telefono }}">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-10">
                                <div class="form-group">
                                    <label for="medico">Especialidades</label>
                                    <select class="form-control" id="especialidad_id" name="especialidad_id">
                                        @foreach ($especialidades as $especialidad)
                                            <option value="{{ $especialidad->id }}" @if ($especialidad->id == $medico->especialidad_id) selected @endif>{{ $especialidad->nombre }}
                                            </option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
            </div>
            <div class="row">
                <div class="offset-4">
                    <button class="btn btn-icon btn-primary " type="submit">
                        <span class="btn-inner--icon"><i class="ni ni-fat-add"></i></span>
                        <span class="btn-inner--text">Editar</span>
                    </button>
                </div>
            </div>
            </form>
        </div>
    </div>
    </div>
    <div class="col-xl-5">
        <div class="card">
            <div class="card-body">
                <img src="{{ asset('images\img2.svg') }} " class="ml-5" alt="" width="350px" height="300px">
            </div>
        </div>
    </div>

@endsection

resources/views/medicos/fecha.blade.php
@extends('plantilla.principal')

@section('contenido')
    <div class="col-xl-7">
        <div class="card">
            <div class="card-body">
                <div class="row align-items-center">
                    <div class="col-6">
                        <h3 class="my-5 ml-4">Buscar citas de un Medico</h3>
                    </div>
                </div>
                <form action="{{ route('medicoCantidad.store') }}" method="POST">
                    {{ csrf_field() }}
                    <div class="pl-lg-4 ml-4">
                       
                        <div class="row">
                            <div class="col-lg-5">
                                <div class="form-group">
                                    <label class="form-control-label" for="fecha">Fecha</label>
                                    <input type="date" id="fecha" name="fecha" class="form-control" placeholder="fecha">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-10">
                                <div class="form-group">
                                    <label for="medico">Medico</label>
                                    <select class="form-control" id="medico" name="medico_id">
                                        @foreach ($medicos as $medico)
                                            <option value="{{ $medico->id }}">{{ $medico->nombre }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="offset-4">
                            <button class="btn btn-icon btn-primary " type="submit">
                                <span class="btn-inner--icon"><i class="ni ni-fat-add"></i></span>
                                <span class="btn-inner--text">buscar</span>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col-xl-5">
        <div class="card">
            <div class="card-body">
                <img src="{{ asset('images\img2.svg') }} " class="ml-5" alt="" width="350px" height="300px">
            </div>
        </div>
    </div>

@endsection

resources/views/medicos/index.blade.php
@extends('plantilla.principal')

@section('contenido')
    <div class="col">
        <div class="card bg-default shadow">
            <div class="card-header bg-transparent border-0">
                <div class="row">
                    <div class="col-9">
                        <h3 class="text-white mb-0">Lista Medicos Registrados</h3>
                    </div>
                    <div class="col-3">
                        <a class="btn btn-icon btn-primary " type="button" href="{{ route('medicos.create') }}">
                            <span class="btn-inner--icon"><i class="ni ni-fat-add"></i></span>
                            <span class="btn-inner--text">Agregar Nuevo</span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table align-items-center table-dark table-flush">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col" class="sort" data-sort="name">Nombre</th>
                            <th scope="col" class="sort" data-sort="name">Apellido</th>
                            <th scope="col" class="sort" data-sort="budget">Especialidad</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody class="list">
                        @foreach ($medicos as $medico)
                            <tr>
                                <td class="budget">{{ $medico->nombre }}</td>
                                <td class="budget">{{ $medico->apellido }}</td>
                                <td class="budget">{{ $medico->especialidades_nombre }}</td>
                                <td class="text-right">
                                    <div class="dropdown">
                                        <a class="btn btn-sm btn-icon-only text-light" href="#" role="button"
                                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="fas fa-ellipsis-v"></i>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">

                                            <a class="dropdown-item" href="{{ route('horarios.show',$medico->id) }}">Horarios</a>

                                            <a class="dropdown-item" href="{{ route('medicos.horas',$medico->id) }}">Hrs laborales</a>

                                            <a class="dropdown-item" href="{{ route('medicos.show',$medico) }}">toda la informacion</a>

                                            <a class="dropdown-item" href="{{ route('medicos.edit',$medico) }}">Editar</a>

                                            <form  action="{{route('medicos.destroy',$medico)}}" method="POST">
                                                {{csrf_field()}}
                                                @method('DELETE')
                                                <button  class="dropdown-item">Eliminar</button>
                                            </form>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>



@endsection

@push('myjs')
@endpush